import { articles as original, creators as authors } from "./data.js";
export const creators = [
  ...authors,
  {
    name: "TRAE 体验官",
    avatar: 0,
    saved: 0,
    likes: 0,
    bio: "在每一次实践中，发现新的可能。",
  },
];
export const viewer = 5;
export const articles = original.map((a, i) => ({
  ...a,
  stamp: Date.UTC(2026, 8, i === 9 ? 18 : 16 - i),
  channelId: [
    "start",
    "agents",
    "makers",
    "work",
    "start",
    "makers",
    "friends",
    "agents",
    "work",
    "start",
    "agents",
    "friends",
  ][i],
}));
export const channels = [
  {
    id: "start",
    name: "TRAE 新手训练营",
    description: "从第一句提示词开始，一起迈出创造的第一步。",
    cover: "start",
    subscribers: 12086,
  },
  {
    id: "makers",
    name: "独立创造者空间站",
    description: "一个想法，一个作品。分享从零到一的实践。",
    cover: "build",
    subscribers: 8362,
  },
  {
    id: "agents",
    name: "Agent 与 MCP 实验室",
    description: "连接工具，拆解任务，探索 AI 协作的新方式。",
    cover: "mcp",
    subscribers: 9631,
  },
  {
    id: "work",
    name: "TRAE Work 效率研究所",
    description: "让重复的工作自动完成，让时间留给创造。",
    cover: "data",
    subscribers: 7286,
  },
  {
    id: "friends",
    name: "TRAE Friends",
    description: "在线相遇，线下见面。和社区伙伴一起成长。",
    cover: "start",
    subscribers: 15826,
  },
  {
    id: "support",
    name: "帮助与反馈",
    description: "问题排查、使用建议和经验交流，都在这里。",
    cover: "mcp",
    subscribers: 4621,
  },
];
const courseSeeds = [
  [
    "first-project",
    "TRAE 从入门到第一个完整项目",
    "start",
    "start",
    "入门",
    0,
    ["认识工作区与项目", "写清楚你的第一个需求", "完成实现与验收"],
  ],
  [
    "mcp-tools",
    "MCP 实战：连接你的开发工具",
    "mcp",
    "agents",
    "进阶",
    4,
    ["理解工具与权限", "配置第一个 MCP 服务", "排查连接问题"],
  ],
  [
    "solo-build",
    "用 SOLO 做出并发布一个作品",
    "build",
    "makers",
    "入门",
    1,
    ["拆解产品目标", "迭代界面与交互", "上线前的检查"],
  ],
  [
    "data-story",
    "从一张表格到交互数据看板",
    "data",
    "work",
    "入门",
    3,
    ["清洗与理解数据", "选择合适的图表", "验证指标与交互"],
  ],
  [
    "rules",
    "项目 Rules 与上下文管理",
    "mcp",
    "start",
    "进阶",
    2,
    ["沉淀项目约定", "维护上下文边界", "复用团队经验"],
  ],
  [
    "testing",
    "让 AI 帮你补齐回归测试",
    "build",
    "makers",
    "进阶",
    2,
    ["识别关键用户路径", "编写有效的测试", "从失败中定位问题"],
  ],
  [
    "agent-basics",
    "读懂 Agent：从工具到完整任务",
    "mcp",
    "agents",
    "入门",
    4,
    ["任务规划与工具调用", "失败与恢复", "设计验收标准"],
  ],
  [
    "workflow",
    "搭建你的个人自动化工作流",
    "data",
    "work",
    "进阶",
    3,
    ["找到重复任务", "连接输入与输出", "验证与日常维护"],
  ],
];
export const courses = courseSeeds.map(
  ([id, title, cover, channelId, level, author, lessons], i) => ({
    id,
    title,
    cover,
    channelId,
    level,
    author,
    featured: i < 4,
    summary:
      "从真实的小任务出发，用可复现的步骤学会" +
      title +
      "。每一节都附有练习和检查清单。",
    lessons: lessons.map((title, j) => ({
      id: `${id}-${j + 1}`,
      title,
      duration: 8 + j * 3,
      body: `这一节我们一起完成「${title}」。\n\n1. 在 TRAE 中新建一个练习项目，写下你希望解决的问题和验收标准。\n2. 把输入、预期输出和限制条件提供给 AI，让它先给出计划。\n3. 选择一个最小步骤执行，观察结果是否符合预期。\n4. 刻意制造一个边界情况，确认系统能给出清晰反馈。\n\n练习：用自己的场景重做一遍，记录一次成功的尝试和一个还需要改进的问题。\n\n检查清单：目标是否具体？结果能否重复验证？失败后知道如何恢复吗？`,
    })),
  }),
);
export const events = [
  {
    id: "friends-shanghai",
    title: "TRAE Friends 上海站：一起把想法变成作品",
    cover: "build",
    channelId: "friends",
    start: "2026-10-24T14:00:00+08:00",
    end: "2026-10-24T17:00:00+08:00",
    place: "上海 · 创造者空间",
    summary:
      "带上你的作品和问题。实战分享、作品体验、自由交流，和创造者一起度过一个下午。",
    agenda: [
      "14:00 签到与自由交流",
      "14:30 从想法到作品：三位创造者分享",
      "15:30 动手共创与作品展示",
      "16:30 自由交流与合影",
    ],
  },
  {
    id: "mcp-live",
    title: "MCP 实战公开课：让工具真正协作起来",
    cover: "mcp",
    channelId: "agents",
    start: "2026-10-10T19:00:00+08:00",
    end: "2026-10-10T20:30:00+08:00",
    place: "线上 · 社区直播",
    summary:
      "从零配置 MCP，用一个完整任务串起文档、数据与代码。带着问题来，边学边试。",
    agenda: [
      "19:00 MCP 的工作方式",
      "19:20 连接工具与任务实践",
      "20:00 常见问题答疑",
    ],
  },
  {
    id: "summer-demo",
    title: "夏日 Demo Day：那些用 TRAE 做出来的小作品",
    cover: "data",
    channelId: "makers",
    start: "2026-08-22T14:00:00+08:00",
    end: "2026-08-22T17:00:00+08:00",
    place: "线上 · 作品分享",
    summary:
      "回顾六位创造者的真实项目，从需求选择到最后一次迭代，聊聊每一个小作品背后的故事。",
    agenda: ["作品展示与经验分享", "创作者圆桌交流"],
    recap: "3",
  },
];
export const prompts = [
  {
    id: "brief",
    title: "把模糊想法变成可执行需求",
    cover: "build",
    category: "开发助手",
    author: 1,
    body: "你是一名产品工程师。请先理解我的目标：\n【在这里填写你的想法】\n列出目标用户、主要使用流程、输入输出和验收标准。标出不确定的信息，先实现最小可用版本。",
  },
  {
    id: "debug",
    title: "一步步定位一个难复现的 BUG",
    cover: "mcp",
    category: "开发助手",
    author: 2,
    body: "请协助定位下面的问题：\n【错误现象、复现步骤、日志】\n先列出最可能的原因和各自验证方式。一次只验证一个假设，修复后补充能复现原问题的测试。",
  },
  {
    id: "dashboard",
    title: "让数据说清楚一个业务问题",
    cover: "data",
    category: "工作提效",
    author: 3,
    body: "请分析我提供的数据。先确认字段含义、时间范围、数据粒度与缺失值。围绕【业务问题】选择指标，给出计算口径，再制作可筛选的图表。不要把相关性当成因果。",
  },
  {
    id: "review",
    title: "给项目做一次上线前检查",
    cover: "start",
    category: "开发助手",
    author: 4,
    body: "请检查当前项目的主要用户流程、空状态、错误恢复和移动端表现。按严重程度列出问题，给出复现步骤与修复建议。每次修复后验证原始问题是否消失。",
  },
  {
    id: "weekly",
    title: "把零散记录整理成一周复盘",
    cover: "data",
    category: "工作提效",
    author: 3,
    body: "根据下面的工作记录，整理本周完成的事情、未完成的原因、已做出的决定，以及下周最重要的行动。保留具体事实，不要添加未发生的工作。\n【粘贴工作记录】",
  },
  {
    id: "learn",
    title: "通过小项目学一个新概念",
    cover: "start",
    category: "学习成长",
    author: 0,
    body: "我想学习【概念】。请用一个能在三十分钟内完成的小项目讲解。先让我尝试判断，再给反馈；每一步说明为什么这样做，并给出可以自检的结果。",
  },
];
